image:
- Visual Studio 2019
- Ubuntu

skip_branch_with_pr: true
stack: python 3.11

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name Aletheia --icon assets/icon.png --product-name Aletheia --product-version "0.0.1"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true


#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  # Ensure that the 'aletheia' directory exists in 'dist' and modify the path accordingly
  - ls dist  # This is for debugging, to check the contents of 'dist' directory
  - tar -czvf aletheia-linux.tar.gz -C dist .

  artifacts:
  - path: aletheia-linux.tar.gz




#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a aletheia-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: aletheia-windows.zip

