image:
- Visual Studio 2019

skip_branch_with_pr: true
stack: python 3.11


install:
- pip install -r requirements.txt

build_script:
- cd app && python -m eel main.py ./static

test: off

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a counter-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: counter-windows.zip



